import type { Product, Category } from "@/lib/types";

// Mock data for development / preview before Supabase is connected.
// Replace these with real queries via src/app/actions/products.ts once
// your Supabase project is configured.

export const mockCategories: Category[] = [
  {
    id: "c1",
    name: "เสื้อผ้า",
    slug: "clothing",
    description: "เสื้อผ้าแฟชั่นทุกสไตล์",
    image_url: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=600&q=80",
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "c2",
    name: "อิเล็กทรอนิกส์",
    slug: "electronics",
    description: "แกดเจ็ตและอุปกรณ์ไอที",
    image_url: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&q=80",
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "c3",
    name: "ของใช้ในบ้าน",
    slug: "home",
    description: "ของแต่งบ้านและเครื่องใช้",
    image_url: "https://images.unsplash.com/photo-1556911220-bff31c812dba?w=600&q=80",
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "c4",
    name: "ความงาม",
    slug: "beauty",
    description: "เครื่องสำอางและสกินแคร์",
    image_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80",
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
];

export const mockProducts: Product[] = [
  {
    id: "p1",
    category_id: "c1",
    name: "เสื้อยืดคอตตอนพรีเมียม",
    slug: "premium-cotton-tshirt",
    description: "เสื้อยืดผ้าคอตตอน 100% นุ่มสบาย ระบายอากาศดี",
    price: 390,
    compare_at_price: 590,
    sku: "CLO-001",
    stock_quantity: 25,
    images: ["https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80"],
    is_active: true,
    is_featured: true,
    meta_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
  },
  {
    id: "p2",
    category_id: "c2",
    name: "หูฟังไร้สาย Bluetooth",
    slug: "wireless-bluetooth-headphones",
    description: "หูฟังไร้สายเสียงคมชัด แบตอึด 30 ชั่วโมง",
    price: 1290,
    compare_at_price: 1990,
    sku: "ELE-001",
    stock_quantity: 12,
    images: ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80"],
    is_active: true,
    is_featured: true,
    meta_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
  },
  {
    id: "p3",
    category_id: "c3",
    name: "แก้วเซรามิกสไตล์มินิมอล",
    slug: "minimal-ceramic-mug",
    description: "แก้วเซรามิกดีไซน์เรียบง่าย ขนาด 350ml",
    price: 250,
    compare_at_price: null,
    sku: "HOM-001",
    stock_quantity: 40,
    images: ["https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=600&q=80"],
    is_active: true,
    is_featured: false,
    meta_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[2],
  },
  {
    id: "p4",
    category_id: "c4",
    name: "เซรั่มบำรุงผิวหน้า",
    slug: "face-serum",
    description: "เซรั่มวิตามินซี ช่วยให้ผิวกระจ่างใส",
    price: 690,
    compare_at_price: 890,
    sku: "BEA-001",
    stock_quantity: 0,
    images: ["https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80"],
    is_active: true,
    is_featured: true,
    meta_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[3],
  },
  {
    id: "p5",
    category_id: "c2",
    name: "คีย์บอร์ดเมคานิคอล RGB",
    slug: "rgb-mechanical-keyboard",
    description: "คีย์บอร์ดเมคานิคอลไฟ RGB สวิตช์ Blue",
    price: 1590,
    compare_at_price: 2290,
    sku: "ELE-002",
    stock_quantity: 8,
    images: ["https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&q=80"],
    is_active: true,
    is_featured: false,
    meta_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[1],
  },
  {
    id: "p6",
    category_id: "c1",
    name: "กางเกงยีนส์ทรงสลิม",
    slug: "slim-fit-jeans",
    description: "กางเกงยีนส์ทรงสลิม ผ้ายืดใส่สบาย",
    price: 890,
    compare_at_price: null,
    sku: "CLO-002",
    stock_quantity: 18,
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&q=80"],
    is_active: true,
    is_featured: false,
    meta_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[0],
  },
  {
    id: "p7",
    category_id: "c3",
    name: "โคมไฟตั้งโต๊ะ LED",
    slug: "led-desk-lamp",
    description: "โคมไฟ LED ปรับแสงได้ 3 ระดับ ถนอมสายตา",
    price: 550,
    compare_at_price: 750,
    sku: "HOM-002",
    stock_quantity: 22,
    images: ["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80"],
    is_active: true,
    is_featured: true,
    meta_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[2],
  },
  {
    id: "p8",
    category_id: "c4",
    name: "ลิปสติกเนื้อแมตต์",
    slug: "matte-lipstick",
    description: "ลิปสติกเนื้อแมตต์ ติดทนนาน สีสวยธรรมชาติ",
    price: 320,
    compare_at_price: 420,
    sku: "BEA-002",
    stock_quantity: 35,
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&q=80"],
    is_active: true,
    is_featured: false,
    meta_title: null,
    meta_description: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: mockCategories[3],
  },
];

export function getFeaturedProducts(): Product[] {
  return mockProducts.filter((p) => p.is_featured);
}

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return mockProducts.filter((p) => p.category?.slug === categorySlug);
}